# Generated by Django 2.0.2 on 2018-02-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=5)),
                ('course_title', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=5)),
                ('mini', models.CharField(max_length=10)),
                ('days', models.CharField(max_length=10)),
                ('begin', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('teaching_location', models.CharField(max_length=50)),
                ('bldg_room', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=50)),
            ],
        ),
    ]
