# Generated by Django 2.0.2 on 2018-02-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180228_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_id']},
        ),
    ]
