# Generated by Django 2.0.2 on 2018-03-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180228_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
